config/routes.rb
Rails.application.routes.draw do

  resources :puppies

  root to: "puppies#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/puppy.rb
class Puppy < ApplicationRecord

  has_one_attached :photo

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/puppies_controller.rb
class PuppiesController < ApplicationController

  def index
    @puppies = Puppy.with_attached_photo
  end

  def new
    @puppy = Puppy.new
  end

  def create
    @puppy = Puppy.create!(puppy_params)

    redirect_to puppies_url
  end 

  private

    def puppy_params
      params.require(:puppy).permit(:photo)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/puppies_helper.rb
module PuppiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpacePuppies</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= image_tag "puppy.svg" %>
      <h1>Space Puppies</h1>

      <%= link_to "New Puppy", new_puppy_url, class: "btn" %>
    </header>

    <main>

      <%= yield %>

    </main>

    <footer>

      <a href="https://thenounproject.com/search/?q=puppy&i=1963353">puppy icon by cinnamon stick from the Noun Project</a>
     

    </footer>
  </body>
</html>

app/views/puppies/_puppy.html.erb
<div class="puppy">
  <%= image_tag puppy.photo.variant(resize_to_fill: [250, 250]) %>
</div>

app/views/puppies/index.html.erb
<% if @puppies.present? %>
  <div class="puppy-grid">
    <%= render @puppies %>
  </div>
<% else %>
  <div class="empty">No puppies — yet!</div>
<% end %>

app/views/puppies/new.html.erb
<h2>New Puppy</h2>

<%= form_with(model: @puppy) do |f| %>

  <div class="form-item">
    <%= f.label :photo %>
    <%= f.file_field :photo, accept: "image/*" %>
  </div>

  <div class="form-item">
    <%= f.submit "Create puppy", class: "btn" %>
  </div>

<% end %>